### PR TITLE
Fix/collection base aspect default

### LINKED ISSUE #290: aspect default productions with collection attributes
It'd be useful to specify a base equation for a collection attribute in a aspect default production, for example:

```silver
aspect default production
top::Expr ::=
{
  top.constraints := case top.inhTy of
  | just(ty) -> [constraintEq(top.synTy, ty)]
  | nothing() -> []
  end;
}
```

to ensure that checked and inferred types are the same when bidirectional typing is used.

### PR DESCRIPTION
**Pull request by unironically**
# Changes
Modified runtime code for collection attributes so that base definitions can be taken from default productions. Essentially the same code as is used to look for synthesized attribute definitions in default productions, seen here:

https://github.com/melt-umn/silver/blob/1184b903f15a865044cabad58cbb17688aebe7d2/runtime/java/src/common/DecoratedNode.java#L521-L532

# Documentation
No new documentation added - small change to runtime.

# Testing
Modified existing collection attribute tests to include cases where base definitions are taken from default productions.

### CODE REVIEW

File: runtime/java/src/common/CollectionAttribute.java [hunk 1]
```diff
@@ -68,7 +68,16 @@ public Object eval(final DecoratedNode context) {
 				} catch(Throwable t) {
 					throw new TraceException("Error evaluating base of collection attribute " + un.getNameOfSynAttr(index) + " via forward of " + un.getName(),t);
 				}
-			}	
+			}	else {
```
Comment (krame505) [inline runtime/java/src/common/CollectionAttribute.java]: Nit, spacing is weird here.

**Comment by krame505** [comment]
I don't quite understand what is being fixed here - is this an instance of https://github.com/melt-umn/silver/issues/290 re-surfacing?  There was a (rather clunky) fix for that made by @remexre in https://github.com/melt-umn/silver/pull/510, is that check still needed with this change?

File: runtime/java/src/common/CollectionAttribute.java (hunk 1 above)
Comment (unironically) [reply runtime/java/src/common/CollectionAttribute.java]: Oopsie - will fix this.

**Comment by unironically** [comment]
This seems to be the same as #290. For instance, running the jar produced by compiling this simple grammar will give `No base defined for collection attribute hello:things in hello:foo`. After fix, program exits with 0 normally.

```
grammar hello;

fun main IO<Integer> ::= largs::[String] =
  do {
    print("Hello, World!\n");
    return if foo().ok then 0 else 1;
  };

synthesized attribute ok::Boolean;
synthesized attribute things::[String] with ++;

nonterminal Foo with ok, things;

production foo
top::Foo ::=
{ top.ok = length(top.things) == 1;
  top.things <- ["thing"]; }

aspect default production top::Foo ::=
{ top.things := []; }
```

Not sure about #510, but I can experiment with removing that check before this is merged. In any case it seems from my testing that #290 was not fixed before this PR.

**Comment by krame505** [comment]
I took another look and this actually seems to be a different issue than #290 - that was collection contribution equations in default prods being ignored when there is a base equation, but this PR deals with the opposite issue: a contribution in a production where the default is defined in the base.  So the fix from #510 should stay.

**Review by krame505 — APPROVED** [review]
